### ISSUE TITLE
没想到竟然以这样的方式找到你，尝试和你探讨问题

### ISSUE THREAD

**Issue by 4801XP** [CMA2401PT/BDXWorkShop#2]
这应该是一种奇怪的方式
我想说，你的六转算法将文件解压后的结果是.mcworld文件或者可以表示我的世界方块位置坐标的文件，那么有没有可能在一个三维的空间中生成该建筑文件的3D预览图呢，这样可以方便fastbuilder用户了解该文件导入后的效果，更好的方便fastbuilder用户的使用

**Comment by CMA2401PT** [comment]
可以，很早就考虑过了，但工作量太大，而且重复造轮子了，所以不写
